### ISSUE TITLE
basic "static file server" middleware

### ISSUE THREAD

**Issue by c-cube** [c-cube/tiny_httpd#12]
```ocaml
val serve_dir: ?upload:bool -> prefix:string -> path:string -> Tiny_httpd.t -> unit
```

registers a path `"/prefix/%s"` for GET-ing files and possibly PUT-ing files if `upload=true`.

The code can be adapted from http_of_dir.

**Comment by craff** [comment]
You can assign this one to me ... I am starting right now...
