### ISSUE TITLE
Problem with mime type of css and js files

### ISSUE THREAD

**Issue by grazil** [c-cube/tiny_httpd#16]
Hello, 

I have some problems with the mime type for css and js files when http_of_dir serve them.

The mimetype given by the server is 'text/plain' which is not accepted by firefox, and the css file is even not loaded.

I saw in the code that it use the 'file' command which is not as good as the command 'mimetype', i believe.

Could you replace it, please?

Thanks by advance!

**Comment by c-cube** [comment]
For me, `http_of_dir` seems to properly recognize html files, but not css files. There is no `mimetype` command on my system though, where does it come from? On what OS are you?

**Comment by c-cube** [comment]
fixed on master.

**Comment by grazil** [comment]
Thanks for the fix. For info, my linux distro is Manjaro (based on Arch). The command "file -i -b style.css" is returning "text/plain; charset=us-ascii".

**Comment by c-cube** [comment]
I have the same issue on arch indeed. I'm just not sure what else to do that is cleaner than a special case.
