### ISSUE TITLE
Function `percent_decode` should not convert the `+` symbol

### ISSUE THREAD

**Issue by smondet** [c-cube/tiny_httpd#18]
Function `percent_decode` should not convert the `+` symbol

See [Tiny_httpd_util.ml#L55](https://github.com/c-cube/tiny_httpd/blob/9961bd1b29c9b68916d96ee1fd242046fc81929c/src/Tiny_httpd_util.ml#L55):

```ocaml
| '+' -> Buffer.add_char buf ' '; incr i (* for query strings *)
```

I'd completely remove that line (the `+` for `SPC` is another language AFAIU).

See also [mirage/ocaml-uri/.../uri.ml#L318](https://github.com/mirage/ocaml-uri/blob/master/lib/uri.ml#L318) which only decodes the percents:

```
ocaml# #require "uri";;
ocaml# Uri.pct_decode "hello%20world, hello+world";;
- : string = "hello world, hello+world"
```

PS: why not using the `uri` library directly BTW? it's pure ocaml and battle-tested.

**Comment by c-cube** [comment]
I didn't want to use Uri as I was trying to get a dependency free library (initially in a single module, oh well). Uri pulls a bunch of stuff,  formerly including sexplib and some ppx. I'll fix this bug of course :)

**Comment by c-cube** [comment]
The `+` is for decoding form-encoded data, btw. See https://en.wikipedia.org/wiki/Percent-encoding#The_application/x-www-form-urlencoded_type
