### ISSUE TITLE
Unix.accept raising exception, not caught

### ISSUE THREAD

**Issue by craff** [c-cube/tiny_httpd#21]
Unix.accept may raise an exception resulting in the death of the server. Typically,
Unix.Unix_error(Unix.EINTR, "accept", "")
even with sigpipe blocked (by default)
I submit the issue and propose a pull request at the same time ...

**Comment by c-cube** [comment]
I'm surprised, but then again signals are really the worst. Thank you for the PR :)

**Comment by craff** [comment]
I was surprised too, but clearly the exception comes from accept ... and maybe the signal in not sigpipe. The bug is not easy to reproduce... more comments in the PR.

**Comment by craff** [comment]
For my this issue is closed ;-)
