### ISSUE TITLE
Provide some level of statistics ?

### ISSUE THREAD

**Issue by craff** [c-cube/tiny_httpd#25]
The PR #23 contains an access to the available connection slot. But it would be useful to 
be able to compute some statistics like
- average and max time to answer a request
- number of request per time unit
- ...
I am ready to write the code ... But don't know exactly what I want.

May be the simplest is to write all request to a sqlite db (time of the arrival of request, time of answer and origin ?) then,
a status page could read that db to print the server status ?

**Comment by craff** [comment]
And this should be optional ?

**Comment by c-cube** [comment]
This should definitely be outside of tiny-httpd, I think it just has to provide some core primitives (like number of active connections), and maybe some instrumentation.

if we get an optional `wrap_query` parameter (maybe a `begin_query: ip -> port -> 'a` and `end_query: 'a -> unit` pair), then you can instrument however you want: prometheus, [tracy](https://github.com/AestheticIntegration/ocaml-tracy), hand rolled sqlite-based analytics, etc. Mechanism, not policy :wink:

**Comment by c-cube** [comment]
Of course a very basic statistics module can be provided alongside `Tiny_httpd_utils`, like `Tiny_httpd_stats` with exactly that kind of pair to pass to `Tiny_httpd.create`.

**Comment by craff** [comment]
I like the idea of a wrapper for connection, the wrapper could have access to both the request and the response though ?
For the default stats, I think something usefull ought to write in a Db from which it is easy to compute average and so on... And therefore hard to provide a default. Except if you have something specific in mind ?

**Comment by c-cube** [comment]
Yes indeed, passing the request and reply to the handler seems like a
good idea. If we were ever to make a web framework, drawing inspiration
from Dream would be a good idea:


```
and handler = request -> response promise

and middleware = handler -> handler
```

so we could have something similar to the `middleware` part, and have
statistics collecting as a simple case.

**Comment by c-cube** [comment]
We already have an internal handler type, which could probably be compatible with a middleware  type `handler -> handler`:


```ocaml

(* a request handler. handles a single request. *)
type cb_path_handler =
  out_channel ->
  byte_stream Request.t ->
  resp:(Response.t -> unit) ->
  unit
```

**Comment by craff** [comment]
The middleware patch + example of stat in echo.ml  solves this issue ?

**Comment by c-cube** [comment]
yeah it's easy to done oneself. done.
