### ISSUE TITLE
Should use magic-mime (or mrmime)

### ISSUE THREAD

**Issue by craff** [c-cube/tiny_httpd#53]
The call for file to get the mime type for small file is very costly.

**Comment by c-cube** [comment]
Hum, are you using `http_of_dir` for high workloads?

Since it's a small companion app to the dependency-less library, I'd rather suggest that we implement a tiny mime type cache. At least if it's based on extensions, I don't know if that's enough…

**Comment by c-cube** [comment]
This should not be an issue for `http_of_dir` for realistic use cases (serving a directory on localhost), I think. For now I prefer to keep things simple.
