### ISSUE TITLE
Accept-encoding and chunked response

### ISSUE THREAD

**Issue by craff** [c-cube/tiny_httpd#59]
Tiny-httpd should not send chunked is
- Accept-encoding is provided but chunked is not mentioned.
Similarly if identity is not in Accept-encoding, this should enforce was is demanded or fail with
the proper error code.

**Comment by c-cube** [comment]
in light of recent discussions, do you think this is still valid? Seems like chunked should always be accepted on both ends, if I understand correctly.

**Comment by craff** [comment]
Simon Cruanes writes:

> in light of recent discussions, do you think this is still valid? Seems like chunked should always be accepted on both ends, if I understand correctly.

Hello,

Yes, it what I understood.

Cheers,
Christophe

--
Christophe Raffalli
tél: +689 87 23 11 48
web: http://raffalli.eu

Ce mail est signé avec pgp (Pièce jointe signature.asc, clef sur https://raffalli.eu/pgp)
This mail is signed pgp (Attachment signature.asc, clef on https://raffalli.eu/pgp)
